language: csharp
mono: 5.12.0

dotnet: 2.1.401

sudo: false 
install:

  # workaround for missing .net 4.5 targing pack

  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

script: 
  - bash ./build.sh test

branches:
  only:
    - master